// apps/angular/src/app/components/invest-form/future-values-info/future-values-info.component.ts
import {CommonModule} from '@angular/common';
import {Component, Input} from '@angular/core';
import {FutureValues} from '../formValues';
import {FutureValueInfoComponent} from '../future-value-info/future-value-info.component';

type PresentFutureValuesProps = FutureValues;

@Component({
  selector: 'future-values-info',
  standalone: true,
  templateUrl: './future-values-info.component.html',
  imports: [CommonModule, FutureValueInfoComponent],
})
export class FutureValuesInfoComponent {
  @Input({required: true}) futureValues!: PresentFutureValuesProps;
}

<div class="space-y-6 mt-4 bg-blue-300 p-6 rounded-lg shadow-md sm:flex sm:space-y-0">
  <future-value-info [futureValue]="futureValues.futureValueOfSavings" class="p-1 sm:w-1/2">
    Future value on savings account
  </future-value-info>

  <future-value-info [futureValue]="futureValues.futureValueOfSP500" class="p-1 sm:w-1/2">
    Future value while invested in S&P 500
  </future-value-info>
</div>

// apps/react/src/components/Form/FutureValuesInfo.tsx
import FutureValueInfo from './FutureValueInfo';
import {FutureValues} from './formValues';

type PresentFutureValuesProps = FutureValues;

function FutureValuesInfo({futureValueOfSavings, futureValueOfSP500}: PresentFutureValuesProps) {
  return (
    <div className="space-y-6 mt-4 bg-blue-300 p-6 rounded-lg shadow-md sm:flex sm:space-y-0">
      <FutureValueInfo futureValue={futureValueOfSavings}>
        Future value on savings account
      </FutureValueInfo>

      <FutureValueInfo futureValue={futureValueOfSP500}>
        Future value while invested in S&P 500
      </FutureValueInfo>
    </div>
  );
}

export default FutureValuesInfo;
