// apps/react/src/components/CountryGuesser/Modals/LoseModal.tsx
import {Country} from '../country';
import Modal from './Modal';

interface LoseModalProps {
  randomCountry: Country;
  handleClose: () => void;
}

function LoseModal({randomCountry, handleClose}: LoseModalProps) {
  return (
    <Modal title="You have not guessed the country :(" handleClose={handleClose}>
      The correct country was: {randomCountry.name.common}.
    </Modal>
  );
}

export default LoseModal;

// apps/angular/src/app/components/country-guesser/modals/lose-modal/lose-modal.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';
import {Country} from '../../country';
import {BaseModalComponent} from '../base-modal/base-modal.component';

@Component({
  selector: 'lose-modal',
  standalone: true,
  templateUrl: './lose-modal.component.html',
  imports: [BaseModalComponent],
})
export class LoseModalComponent {
  @Input({required: true}) randomCountry!: Country;

  @Output() handleClose = new EventEmitter<void>();
}

<base-modal [title]="'You have not guessed the country :('" (handleClose)="handleClose.emit()">
  The correct country was: {{ randomCountry.name.common }}.
</base-modal>
