// apps/react/src/components/CountryGuesser/Modals/WinModal.tsx
import {Country} from '../country';
import Modal from './Modal';

interface WinModalProps {
  randomCountry: Country;
  totalGuessesNeeded: number;
  handleClose: () => void;
}

function WinModal({randomCountry, totalGuessesNeeded, handleClose}: WinModalProps) {
  return (
    <Modal
      title="Congratulations, you have guessed the country correctly!"
      handleClose={handleClose}
    >
      The correct country was: <strong>{randomCountry.name.common}</strong>.
      <br />
      You have guessed the country in {totalGuessesNeeded}{' '}
      {totalGuessesNeeded > 1 ? 'tries' : 'try'}.
    </Modal>
  );
}

export default WinModal;

// apps/angular/src/app/components/country-guesser/modals/win-modal/win-modal.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';
import {Country} from '../../country';
import {BaseModalComponent} from '../base-modal/base-modal.component';

@Component({
  selector: 'win-modal',
  standalone: true,
  templateUrl: './win-modal.component.html',
  imports: [BaseModalComponent],
})
export class WinModalComponent {
  @Input({required: true}) randomCountry!: Country;
  @Input({required: true}) totalGuessesNeeded = 0;

  @Output() handleClose = new EventEmitter<void>();
}

<base-modal
  [title]="'Congratulations, you have guessed the country correctly!'"
  (handleClose)="handleClose.emit()"
>
  The correct country was: <strong>{{ randomCountry.name.common }}</strong
  >.
  <br />
  You have guessed the country in {{ totalGuessesNeeded }}
  {{ totalGuessesNeeded > 1 ? 'tries' : 'try' }}.
</base-modal>
