// apps/svelte/src/lib/components/invest-form/FutureValuesInfo.svelte
<script lang="ts">
  import FutureValueInfo from './FutureValueInfo.svelte';
  import {type FutureValues} from './types';

  export let futureValues: FutureValues;
</script>

<div class="space-y-6 mt-4 bg-blue-300 p-6 rounded-lg shadow-md sm:flex sm:space-y-0">
  <FutureValueInfo futureValue={futureValues.futureValueOfSavings}>
    Future value on savings account
  </FutureValueInfo>

  <FutureValueInfo futureValue={futureValues.futureValueOfSP500}>
    Future value after investing in S&P 500
  </FutureValueInfo>
</div>

// apps/react/src/components/InvestForm/FutureValuesInfo.tsx
import FutureValueInfo from './FutureValueInfo';
import {FutureValues} from './types';

type PresentFutureValuesProps = FutureValues;

function FutureValuesInfo({futureValueOfSavings, futureValueOfSP500}: PresentFutureValuesProps) {
  return (
    <div className="space-y-6 mt-4 bg-blue-300 p-6 rounded-lg shadow-md sm:flex sm:space-y-0">
      <FutureValueInfo futureValue={futureValueOfSavings}>
        Future value on savings account
      </FutureValueInfo>

      <FutureValueInfo futureValue={futureValueOfSP500}>
        Future value after investing in S&P 500
      </FutureValueInfo>
    </div>
  );
}

export default FutureValuesInfo;
