// apps/angular/src/app/components/invest-form/input-label/input-label.component.ts
import {CommonModule} from '@angular/common';
import {Component, Input} from '@angular/core';

@Component({
  selector: 'input-label',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './input-label.component.html',
})
export class InputLabelComponent {
  @Input({required: true}) id = '';
}

<label [htmlFor]="id" class="block mb-2 text-sm font-medium text-gray-700">
  <ng-content />
</label>

// apps/react/src/components/InvestForm/InputLabel.tsx
import {ReactNode} from 'react';

interface LabelProps {
  id: string;
  children: ReactNode;
}

function InputLabel({id, children}: LabelProps) {
  return (
    <label htmlFor={id} className="block mb-2 text-sm font-medium text-gray-700">
      {children}
    </label>
  );
}

export default InputLabel;
