// apps/react/src/pages/CountryGuesserWrapper.tsx
import {PropsWithChildren} from 'react';
import useCountries from '../components/CountryGuesser/useCountries';
import CountryGuesser from '../components/CountryGuesser/CountryGuesser';
import LoadingSkeleton from '../components/CountryGuesser/LoadingSkeleton';
import ErrorAlert from '../components/CountryGuesser/ErrorAlert';

const WrapperDiv = ({children}: PropsWithChildren) => {
  return (
    <div className="container flex flex-col justify-center justify-items-center mx-auto">
      {children}
    </div>
  );
};

function CountryGuesserWrapper() {
  const [countries, error] = useCountries();

  if (error) {
    return (
      <WrapperDiv>
        <ErrorAlert message={error.message} />
      </WrapperDiv>
    );
  }

  if (countries.length > 0) {
    return <CountryGuesser countries={countries} />;
  }

  return (
    <WrapperDiv>
      <LoadingSkeleton />
    </WrapperDiv>
  );
}

export default CountryGuesserWrapper;

// apps/svelte/src/lib/pages/CountryGuesserWrapper.svelte
<script lang="ts">
  import CountryGuesser from '../components/country-guesser/CountryGuesser.svelte';
  import {mockedData} from '../components/country-guesser/mockedData';

  let countries = mockedData;
  let error = false;
</script>

{#if error}
  <div class="container flex flex-col justify-center justify-items-center mx-auto">ErrorAlert</div>
{:else if countries.length > 0}
  <CountryGuesser {countries} />;
{:else}
  <div class="container flex flex-col justify-center justify-items-center mx-auto">
    LoadingSkeleton
  </div>
{/if}
