// apps/angular/src/app/components/translator/language-dropdown/language-dropdown.component.ts
import {CommonModule} from '@angular/common';
import {Component, EventEmitter, Input, Output} from '@angular/core';
import {DropdownComponent, Option} from '../../dropdown/dropdown.component';

@Component({
  selector: 'language-dropdown',
  standalone: true,
  templateUrl: './language-dropdown.component.html',
  imports: [CommonModule, DropdownComponent],
})
export class LanguageDropdownComponent {
  @Input() options: ReadonlyArray<Option> = [];

  @Output() languageChange = new EventEmitter<Option>();

  protected handleChangeSelected(selectedLanguage: Option): void {
    this.languageChange.emit(selectedLanguage);
  }
}

<dropdown
  [options]="options"
  [defaultValue]="options[0]"
  placeholder="Select a language for translation"
  (changeSelected)="handleChangeSelected($event)"
  variant="secondary"
/>

// apps/svelte/src/lib/components/translator/LanguageDropdown.svelte
<script lang="ts">
  import Dropdown from '../dropdown/Dropdown.svelte';
  import {type Option} from '../dropdown/types';

  export let options: ReadonlyArray<Option>;
  export let onChange: (selectedLanguage: Option | null) => void;
</script>

<Dropdown
  {options}
  {onChange}
  defaultValue={options[0]}
  placeholder="Select a language for translation"
  variant="secondary"
/>
