// apps/svelte/src/lib/components/country-guesser/modals/LoseModal.svelte
<script lang="ts">
  import {type Country} from '../country';
  import BaseModal from './BaseModal.svelte';

  export let randomCountry: Country;
  export let handleClose: () => void;
</script>

<BaseModal title="You have not guessed the country :(" {handleClose}>
  The correct country was: {randomCountry.name.common}.
</BaseModal>

// apps/react/src/components/CountryGuesser/Modals/LoseModal.tsx
import {Country} from '../country';
import BaseModal from './BaseModal';

interface LoseModalProps {
  randomCountry: Country;
  handleClose: () => void;
}

function LoseModal({randomCountry, handleClose}: LoseModalProps) {
  return (
    <BaseModal title="You have not guessed the country :(" handleClose={handleClose}>
      The correct country was: {randomCountry.name.common}.
    </BaseModal>
  );
}

export default LoseModal;
