// apps/svelte/src/lib/components/country-guesser/modals/WinModal.svelte
<script lang="ts">
  import {type Country} from '../country';
  import BaseModal from './BaseModal.svelte';

  export let randomCountry: Country;
  export let totalGuessesNeeded: number;
  export let handleClose: () => void;
</script>

<BaseModal title="Congratulations, you have guessed the country correctly!" {handleClose}>
  The correct country was: <strong>{randomCountry.name.common}</strong>.
  <br />
  You have guessed the country in {totalGuessesNeeded}
  {totalGuessesNeeded > 1 ? 'tries' : 'try'}.
</BaseModal>

// apps/react/src/components/CountryGuesser/Modals/WinModal.tsx
import {Country} from '../country';
import BaseModal from './BaseModal';

interface WinModalProps {
  randomCountry: Country;
  totalGuessesNeeded: number;
  handleClose: () => void;
}

function WinModal({randomCountry, totalGuessesNeeded, handleClose}: WinModalProps) {
  return (
    <BaseModal
      title="Congratulations, you have guessed the country correctly!"
      handleClose={handleClose}
    >
      The correct country was: <strong>{randomCountry.name.common}</strong>.
      <br />
      You have guessed the country in {totalGuessesNeeded}{' '}
      {totalGuessesNeeded > 1 ? 'tries' : 'try'}.
    </BaseModal>
  );
}

export default WinModal;
