// apps/svelte/src/lib/pages/CountryGuesserWrapper.svelte
<script lang="ts">
  import CountryGuesser from '../components/country-guesser/CountryGuesser.svelte';
  import {mockedData} from '../components/country-guesser/mockedData';

  let countries = mockedData;
  let error = false;
</script>

{#if error}
  <div class="container flex flex-col justify-center justify-items-center mx-auto">ErrorAlert</div>
{:else if countries.length > 0}
  <CountryGuesser {countries} />;
{:else}
  <div class="container flex flex-col justify-center justify-items-center mx-auto">
    LoadingSkeleton
  </div>
{/if}

// apps/angular/src/app/pages/country-guesser-wrapper/country-guesser-wrapper.component.ts
import {Component} from '@angular/core';
import {Country} from '../../components/country-guesser/country';
import {CountryGuesserComponent} from '../../components/country-guesser/country-guesser.component';
import {LoadingSkeletonComponent} from '../../components/country-guesser/loading-skeleton/loading-skeleton.component';
import {mockedData} from '../../components/country-guesser/mockedData';

@Component({
  selector: 'country-guesser-wrapper',
  standalone: true,
  templateUrl: './country-guesser-wrapper.component.html',
  imports: [CountryGuesserComponent, LoadingSkeletonComponent],
})
export class CountryGuesserWrapperComponent {
  protected countries: ReadonlyArray<Country> = mockedData;
}

<!-- error -->

@if (countries.length > 0) {
  <country-guesser [countries]="countries" />
} @else {
  <div class="container flex flex-col justify-center justify-items-center mx-auto">
    <loading-skeleton />
  </div>
}
