// apps/svelte/src/lib/components/translator/LanguageDropdown.svelte
<script lang="ts">
  import Dropdown from '../dropdown/Dropdown.svelte';
  import {type Option} from '../dropdown/types';

  export let options: ReadonlyArray<Option>;
  export let onChange: (selectedLanguage: Option | null) => void;
</script>

<Dropdown
  {options}
  {onChange}
  defaultValue={options[0]}
  placeholder="Select a language for translation"
  variant="secondary"
/>

// apps/react/src/components/Translator/LanguageDropdown.tsx
import Dropdown, {Option} from '../Dropdown/Dropdown';

interface LanguageDropdown {
  options: ReadonlyArray<Option>;
  onChange: (selectedLanguage: Option | null) => void;
}

function LanguageDropdown({options, onChange}: LanguageDropdown) {
  return (
    <Dropdown
      key='language-dropdown'
      options={options}
      defaultValue={options[0]}
      placeholder='Select a language for translation'
      onChange={onChange}
      variant='secondary'
    />
  );
}

export default LanguageDropdown;
