// apps/angular/src/app/components/translator/translator.component.ts
import {CommonModule} from '@angular/common';
import {Component} from '@angular/core';
import {Subject, catchError, debounceTime, distinctUntilChanged, throwError} from 'rxjs';
import {Option} from '../dropdown/dropdown.component';
import {LanguageDropdownComponent} from './language-dropdown/language-dropdown.component';
import {languages as availableLanguages} from './languages';
import {TranslationInputComponent} from './translation-input/translation-input.component';
import {TranslationOutputComponent} from './translation-output/translation-output.component';
import {TranslationService} from './translation/translation.service';

@Component({
  selector: 'translator',
  standalone: true,
  templateUrl: './translator.component.html',
  imports: [
    CommonModule,
    LanguageDropdownComponent,
    TranslationInputComponent,
    TranslationOutputComponent,
  ],
})
export class TranslatorComponent {
  private inputValuesChanges = new Subject<string>();

  protected languages: ReadonlyArray<Option> = availableLanguages;
  protected inputText = '';
  protected outputText = '';
  protected outputLanguage = this.languages[0].value;
  protected loading = false;
  protected error: Error | null = null;

  constructor(private readonly translationService: TranslationService) {
    this.setupInputChangeSubscription();
  }

  protected handleInputTextChange(inputText: string): void {
    this.inputText = inputText;
    this.inputValuesChanges.next(inputText);
  }

  protected handleLanguageChange(outputLanguage: Option): void {
    this.outputLanguage = outputLanguage.value;
    this.inputValuesChanges.next(outputLanguage.value);
  }

  private setupInputChangeSubscription(): void {
    this.inputValuesChanges
      .pipe(debounceTime(300), distinctUntilChanged())
      .subscribe(() => this.triggerTranslation());
  }

  private triggerTranslation(): void {
    this.loading = true;

    this.translationService
      .getTranslation(this.inputText, this.outputLanguage)
      .pipe(catchError(error => this.handleError(error)))
      .subscribe({
        next: response => (this.outputText = response),
        error: error => (this.error = error),
        complete: () => (this.loading = false),
      });
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private handleError(error: any) {
    return throwError(
      () => new Error(`Something went wrong: ${error.status} Error. Please reload the page.`),
    );
  }
}

<div class="container mx-auto">
  <div class="flex border border-b-0 py-1 items-center">
    <h3 class="w-1/2 pl-2">Automatické rozpoznávání jazyka</h3>

    <language-dropdown [options]="languages" (languageChange)="handleLanguageChange($event)" />
  </div>

  <div class="flex text-xl">
    <translation-input
      [inputText]="inputText"
      (setInputText)="handleInputTextChange($event)"
      class="relative w-1/2"
    />

    <translation-output
      [inputText]="inputText"
      [outputText]="outputText"
      [loading]="loading"
      [error]="error"
      class="relative w-1/2"
    />
  </div>
</div>

// apps/react/src/components/Translator/Translator.tsx
import {useEffect, useRef, useState} from 'react';
import TranslationInput from './TranslationInput';
import TranslationOutput from './TranslationOutput';
import {languages} from './languages';
import LanguageDropdown from './LanguageDropdown';

function Translator() {
  const [inputText, setInputText] = useState('');
  const [outputText, setOutputText] = useState('');
  const [outputLanguage, setOutputLanguage] = useState(languages[0].value);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const abortControllerRef = useRef<AbortController | null>(null);
  const delayTimerRef = useRef<number>();

  useEffect(() => {
    return () => {
      clearTimeout(delayTimerRef.current);
      abortControllerRef?.current?.abort();
    };
  }, []);

  useEffect(() => {
    const handleTranslation = async () => {
      if (!inputText.length) return;

      abortControllerRef.current?.abort();
      abortControllerRef.current = new AbortController();
      setLoading(true);

      const parsedInputText = inputText.replace(/\n/g, ' ');
      const url = `${import.meta.env.VITE_RAPID_API_BASE_URL}${outputLanguage}${
        import.meta.env.VITE_RAPID_API_QUERY_PARAMS
      }`;
      const options = {
        method: 'POST',
        headers: {
          'content-type': 'application/json',
          'X-RapidAPI-Key': import.meta.env.VITE_RAPID_API_KEY,
          'X-RapidAPI-Host': 'microsoft-translator-text.p.rapidapi.com',
        },
        body: `[{"Text":"${parsedInputText}"}]`,
        signal: abortControllerRef.current?.signal,
      };

      try {
        const response = await fetch(url, options);

        if (!response.ok) {
          throw new Error(`Something went wrong: ${response.status} Error. Please reload the page.`);
        }

        const result = await response.json();
        const translatedText = result[0].translations[0].text as string;
        setOutputText(translatedText);
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
      } catch (error: any) {
        if (error.name === 'AbortError') return;

        setError(error);
      } finally {
        setLoading(false);
      }
    };

    clearTimeout(delayTimerRef.current);

    delayTimerRef.current = setTimeout(() => handleTranslation(), 300);

    return () => clearTimeout(delayTimerRef.current);
  }, [inputText, outputLanguage]);

  return (
    <div className='container mx-auto'>
      <div className='flex border border-b-0 py-1 items-center'>
        <h3 className='w-1/2 pl-2'>Automatické rozpoznávání jazyka</h3>

        <LanguageDropdown
          options={languages}
          onChange={selectedLanguage =>
            selectedLanguage && setOutputLanguage(selectedLanguage.value)
          }
        />
      </div>

      <div className='flex text-xl'>
        <TranslationInput inputText={inputText} setInputText={setInputText} />

        <TranslationOutput
          inputText={inputText}
          outputText={outputText}
          loading={loading}
          error={error}
        />
      </div>
    </div>
  );
}

export default Translator;
