// apps/svelte/src/lib/pages/DropdownWrapper.svelte
<script lang="ts">
  import Dropdown from '../components/dropdown/Dropdown.svelte';
  import {type DropdownSize} from '../components/dropdown/dropdownSize';
  import {type DropdownVariant} from '../components/dropdown/dropdownVariants';
  import {type Option} from '../components/dropdown/types';

  const dropdownVariants: ReadonlyArray<DropdownVariant> = [
    'primary',
    'secondary',
    'neutral',
    'light',
    'dark',
    'info',
    'success',
    'warning',
    'error',
  ];

  const colors = [
    {label: 'Alice Blue', value: '#F0F8FF'},
    {label: 'Antique White', value: '#FAEBD7'},
    {label: 'Aqua', value: '#00FFFF'},
    {label: 'Aquamarine', value: '#7FFFD4'},
    {label: 'Azure', value: '#F0FFFF'},
    {label: 'Beige', value: '#F5F5DC'},
  ];

  const sizes: ReadonlyArray<DropdownSize> = ['sm', 'md', 'lg'];

  let selectedColor: Option | null = null;
</script>

{#each sizes as size}
  <div class="flex gap-2 justify-center items-center h-20">
    {#each dropdownVariants as variant}
      <Dropdown
        options={colors}
        defaultValue={selectedColor}
        placeholder="Select a color"
        onChange={option => (selectedColor = option)}
        {size}
        {variant}
      />
    {/each}
  </div>
{/each}

// apps/angular/src/app/pages/dropdown-wrapper/dropdown-wrapper.component.ts
import {CommonModule} from '@angular/common';
import {Component} from '@angular/core';
import {DropdownComponent, Option} from '../../components/dropdown/dropdown.component';
import {DropdownSize} from '../../components/dropdown/dropdownSize';
import {DropdownVariant} from '../../components/dropdown/dropdownVariants';

@Component({
  selector: 'dropdown-wrapper',
  standalone: true,
  imports: [CommonModule, DropdownComponent],
  templateUrl: './dropdown-wrapper.component.html',
})
export class DropdownWrapperComponent {
  protected dropdownVariants: ReadonlyArray<DropdownVariant> = [
    'primary',
    'secondary',
    'neutral',
    'light',
    'dark',
    'info',
    'success',
    'warning',
    'error',
  ];
  protected colors: ReadonlyArray<Option> = [
    {label: 'Alice Blue', value: '#F0F8FF'},
    {label: 'Antique White', value: '#FAEBD7'},
    {label: 'Aqua', value: '#00FFFF'},
    {label: 'Aquamarine', value: '#7FFFD4'},
    {label: 'Azure', value: '#F0FFFF'},
    {label: 'Beige', value: '#F5F5DC'},
  ];
  protected sizes: ReadonlyArray<DropdownSize> = ['sm', 'md', 'lg'];

  protected selectedColor: Option | null = null;

  protected handleChangeSelected(selectedColor: Option): void {
    this.selectedColor = selectedColor;
  }
}

@for (size of sizes; track size) {
  <div class="flex gap-2 justify-center items-center h-20">
    @for (variant of dropdownVariants; track variant) {
      <dropdown
        [options]="colors"
        [defaultValue]="selectedColor"
        placeholder="Select a color"
        (changeSelected)="handleChangeSelected($event)"
        [variant]="variant"
        [size]="size"
      />
    }
  </div>
}
