// apps/react/src/components/CountryGuesser/HintBoxes/HintBox.tsx
import {ImgHTMLAttributes, ReactNode} from 'react';

export interface HintBoxProps {
  title: string;
  abbrTitle: string;
  hint: string | null;
  hintIcon: ReactNode;
  hintEnabled?: boolean;
  flagImage?: ImgHTMLAttributes<HTMLImageElement>;
}

function HintBox({title, abbrTitle, hint = '?', hintIcon, hintEnabled, flagImage}: HintBoxProps) {
  const showFlagHint = flagImage && hintEnabled;

  return (
    <abbr
      title={abbrTitle}
      className="grid aspect-square max-w-40 md:max-w-56 rounded-lg items-center border-2 border-gray-600 no-underline"
    >
      <div className="text-center">
        <div>{showFlagHint ? <img {...flagImage} /> : hintIcon}</div>
        <h3 className="text-center">{title}</h3>
        <p>{hintEnabled ? hint : '?'}</p>
      </div>
    </abbr>
  );
}

export default HintBox;

// apps/angular/src/app/components/country-guesser/hint-boxes/hint-box/hint-box.component.ts
import {NgComponentOutlet} from '@angular/common';
import {Component, Input, OnInit, Type} from '@angular/core';

type HintComponent = Type<unknown>;

interface FlagImage {
  src: string;
  alt: string;
}

export interface HintBox {
  title: string;
  abbrTitle: string;
  hint: string;
  hintComponent: HintComponent;
  hintEnabled?: boolean;
  flagImage?: FlagImage;
}

@Component({
  selector: 'hint-box',
  standalone: true,
  imports: [NgComponentOutlet],
  templateUrl: './hint-box.component.html',
})
export class HintBoxComponent implements OnInit {
  protected showFlagHint = false;

  @Input({required: true}) title = '';
  @Input({required: true}) abbrTitle = '';
  @Input({required: true}) hint = '?';
  @Input({required: true}) hintComponent!: HintComponent;
  @Input() hintEnabled = false;
  @Input() flagImage?: FlagImage;

  public ngOnInit() {
    this.showFlagHint = !!this.flagImage && this.hintEnabled;
  }
}

<abbr
  [title]="abbrTitle"
  class="grid aspect-square max-w-40 md:max-w-56 rounded-lg items-center border-2 border-gray-600 no-underline"
>
  <div class="text-center">
    @if (showFlagHint) {
      <img [src]="flagImage?.src" [alt]="flagImage?.alt" />
    } @else {
      <ng-container *ngComponentOutlet="hintComponent" />
    }

    <h3 class="text-center">{{ title }}</h3>
    <p>{{ hintEnabled ? hint : '?' }}</p>
  </div>
</abbr>
