// apps/react/src/components/Button.tsx
interface ButtonProps {
  className: string;
  onClick: () => void;
  children: React.ReactNode;
}

function Button({className, onClick, children}: ButtonProps): JSX.Element {
  return (
    <button className={`px-4 py-2 rounded-md focus:outline-none ${className}`} onClick={onClick}>
      {children}
    </button>
  );
}

export default Button;

// apps/vue/src/components/Button.vue
<script setup lang="ts">
interface Props {
  className: string;
  onClick: () => void;
  textContent: string;
}

const props = defineProps<Props>();
</script>

<template>
  <button
    :class="`px-4 py-2 rounded-md focus:outline-none ${props.className}`"
    @click="props.onClick"
  >
    {{ props.textContent }}
  </button>
</template>
