// apps/svelte/src/lib/components/country-guesser/LoadingSkeleton.svelte
<script lang="ts">
  // Pole s 6 prázdnými položkami.
  const items = Array.from({length: 6});
</script>

<div role="status" class="animate-pulse">
  {#each items as item, index}
    <div
      class={`${index === 0 ? '!h-6' : 'h-4'} 
        bg-gray-300 rounded-full dark:bg-gray-400 w-full mt-4`}
    ></div>
  {/each}
  <span class="sr-only">Loading...</span>
</div>

<!-- Převzato a upraveno podle: -->
<!-- https://flowbite.com/docs/components/skeleton/ -->

// apps/react/src/components/CountryGuesser/LoadingSkeleton.tsx
function LoadingSkeleton() {
  return (
    <div role="status" className="animate-pulse">
      {/* Pole s 6 prázdnými položkami. */}
      {Array.from({length: 6}, (_, index) => (
        <div
          key={index}
          className={`${index === 0 ? '!h-6' : 'h-4'} bg-gray-300 rounded-full dark:bg-gray-400 w-full mt-4`}
        ></div>
      ))}
      <span className="sr-only">Loading...</span>
    </div>
  );
}

export default LoadingSkeleton;

// Převzato a upraveno podle:
// https://flowbite.com/docs/components/skeleton/
