// apps/angular/src/app/components/layout/footer/footer.component.ts
import {Component} from '@angular/core';
import {RouterLink} from '@angular/router';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './footer.component.html',
})
export class FooterComponent {}

<footer class="p-4 bg-gray-100 md:p-8 lg:p-8 dark:bg-gray-800">
  <div class="mx-auto max-w-screen-xl text-center">
    <p class="mb-6 text-gray-500 dark:text-gray-400">
      Vytvořeno jako bakalářská práce na Slezské univerzitě v Opavě
    </p>
    <ul class="flex flex-wrap justify-center items-center mb-6 text-gray-900 dark:text-white">
      <li>
        <a
          href="https://github.com/lukyncze/bachelor-thesis/blob/main/thesis/sablona_ukazka.pdf"
          target="_blank"
          rel="noopener noreferrer"
          class="mr-4 hover:underline md:mr-6"
        >
          Text práce
        </a>
      </li>
      <li>
        <a
          href="https://github.com/lukyncze/bachelor-thesis"
          target="_blank"
          rel="noopener noreferrer"
          class="hover:underline"
        >
          Github repozitář
        </a>
      </li>
    </ul>
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">
      &copy; 2023-2024 Lukáš Sukeník
    </span>
  </div>
</footer>

<!-- Převzato a upraveno podle: -->
<!-- https://flowbite.com/blocks/marketing/footer/ -->

// apps/svelte/src/lib/components/layout/Footer.svelte
<footer class="p-4 bg-gray-100 md:p-8 lg:p-8 dark:bg-gray-800">
  <div class="mx-auto max-w-screen-xl text-center">
    <p class="mb-6 text-gray-500 dark:text-gray-400">
      Vytvořeno jako bakalářská práce na Slezské univerzitě v Opavě
    </p>
    <ul class="flex flex-wrap justify-center items-center mb-6 text-gray-900 dark:text-white">
      <li>
        <a
          href="https://github.com/lukyncze/bachelor-thesis/blob/main/thesis/sablona_ukazka.pdf"
          target="_blank"
          rel="noopener noreferrer"
          class="mr-4 hover:underline md:mr-6">Text práce</a
        >
      </li>
      <li>
        <a
          href="https://github.com/lukyncze/bachelor-thesis"
          target="_blank"
          rel="noopener noreferrer"
          class="hover:underline">Github repozitář</a
        >
      </li>
    </ul>
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">
      &copy; 2023-2024 Lukáš Sukeník
    </span>
  </div>
</footer>

<!-- Převzato a upraveno podle: -->
<!-- https://flowbite.com/blocks/marketing/footer/ -->
