// apps/angular/src/app/components/country-guesser/country-guess-input/country-guess-input.component.ts
import {CommonModule} from '@angular/common';
import {Component, EventEmitter, Input, OnChanges, Output} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {Countries} from '../country';
import {GuessedCountries} from '../country-guesser.component';

const countryHintsCount = 8;

@Component({
  selector: 'country-guess-input',
  standalone: true,
  templateUrl: './country-guess-input.component.html',
  imports: [CommonModule, FormsModule],
})
export class CountryGuessInputComponent implements OnChanges {
  private countriesWithoutAlreadyGuessed: Countries = [];
  protected filteredCountries: Countries = [];
  protected currentGuess = '';
  protected isOpen = false;
  protected isValidGuess = false;
  protected selectedGuessIndex = 0;

  @Input({required: true}) public countries: Countries = [];
  @Input({required: true}) public guessedCountries: GuessedCountries = [];

  @Output() public evaluateGuessAndUpdateState = new EventEmitter<string>();

  public ngOnChanges(): void {
    this.countriesWithoutAlreadyGuessed = this.countries.filter(
      country => !this.guessedCountries.includes(country.name.common),
    );
    this.filteredCountries = this.countriesWithoutAlreadyGuessed.slice(0, countryHintsCount);
  }

  protected handleGuessButtonClick(): void {
    if (this.isValidGuess) {
      this.evaluateGuessAndUpdateState.emit(this.currentGuess);
      this.handleChangeSelectedGuess('');
    }
  }

  protected handleChangeSelectedGuess(guessedCountry: string): void {
    this.updateGuessAndFilteredCountries(guessedCountry);
    this.isOpen = false;
  }

  protected handleInputChange(value: string): void {
    const formattedGuess = this.convertToFormattedGuess(value);
    this.updateGuessAndFilteredCountries(formattedGuess);
  }

  protected handleKeyDown(event: KeyboardEvent): void {
    if (!this.isOpen) return;

    if (event.key === 'ArrowUp') {
      this.changeSelectedGuessIndex(-1);
      event.preventDefault();
    } else if (event.key === 'ArrowDown') {
      this.changeSelectedGuessIndex(1);
      event.preventDefault();
    } else if (event.key === 'Enter' && this.filteredCountries.length > 0) {
      this.handleChangeSelectedGuess(this.filteredCountries[this.selectedGuessIndex].name.common);
    } else if (event.key === 'Escape') {
      this.isOpen = false;
    }
  }

  private updateGuessAndFilteredCountries(guessedCountry: string): void {
    this.currentGuess = guessedCountry;

    const filteredCountries = this.getFilteredCountries();
    const isValidGuess = !!filteredCountries.find(({name}) => name.common === this.currentGuess);

    this.isValidGuess = isValidGuess;
    this.filteredCountries = filteredCountries;
    this.clampSelectedGuessIndex();
  }

  private getFilteredCountries() {
    const filteredCountries = this.countriesWithoutAlreadyGuessed.filter(country =>
      country.name.common.toLowerCase().includes(this.currentGuess.toLowerCase()),
    );
    return filteredCountries.slice(0, countryHintsCount);
  }

  private clampSelectedGuessIndex(): void {
    if (
      this.filteredCountries.length > 0 &&
      this.selectedGuessIndex >= this.filteredCountries.length
    ) {
      this.selectedGuessIndex = this.filteredCountries.length - 1;
    }
  }

  private changeSelectedGuessIndex(value: number): void {
    if (this.selectedGuessIndex + value < 0) return;
    if (this.selectedGuessIndex + value >= this.filteredCountries.length) return;

    this.selectedGuessIndex += value;
  }

  private convertToFormattedGuess(guess: string) {
    const [firstLetter, ...rest] = guess;
    return firstLetter ? `${firstLetter.toUpperCase()}${rest.join('').toLowerCase()}` : '';
  }
}

<div class="relative group">
  <div class="flex">
    <input
      type="text"
      [ngModel]="currentGuess"
      (ngModelChange)="handleInputChange($event)"
      (click)="isOpen = true"
      (keydown)="handleKeyDown($event)"
      class="block rounded-md w-full p-2 shadow-sm bg-gray-100 border border-gray-400 lg:w-[20rem] xl:w-[24rem]"
    />

    <button
      class="rounded-md w-40 !p-2 grid place-content-center border border-gray-400 bg-green-800 text-white animate-pulse lg:w-28 xl:w-32 hover:animate-none hover:bg-green-900 disabled:animate-none disabled:bg-red-800"
      (click)="handleGuessButtonClick()"
      [disabled]="!isValidGuess"
    >
      Take a guess
    </button>
  </div>

  <div
    class="flex flex-col absolute top-18 w-full duration-150 opacity-0 pointer-events-none bg-gray-200 rounded-lg border border-gray-300"
    [ngClass]="{'group-focus-within:opacity-100 group-focus-within:pointer-events-auto': isOpen}"
  >
    @if (filteredCountries.length > 0) {
      @for (filteredCountry of filteredCountries; track filteredCountry) {
        <!-- $index reprezentuje aktuální index ve for smyčce. -->
        <button
          (click)="handleChangeSelectedGuess(filteredCountry.name.common)"
          class="rounded-lg p-2"
          [ngClass]="{'bg-gray-300': selectedGuessIndex === $index}"
        >
          {{ filteredCountry.flag }} {{ filteredCountry.name.common }}
        </button>
      }

      @if (filteredCountries.length === 1) {
        <span class="rounded-lg p-2 text-center">
          Hit enter to select <b>{{ filteredCountries[0].name.common }}</b>
        </span>
      }
    } @else {
      <div class="rounded-lg p-2">No country found. Please, try to change your input.</div>
    }
  </div>

  @if (!filteredCountries.length) {
    <div class="rounded-lg mt-2">No country found. Please, try to change your input.</div>
  }
  @if (currentGuess.length && filteredCountries.length && !isValidGuess) {
    <div class="rounded-lg mt-2">Please enter/select a valid full country name.</div>
  }
  @if (!currentGuess.length) {
    <div class="rounded-lg mt-2">Enter a country you want to guess.</div>
  }
</div>

// apps/svelte/src/lib/components/country-guesser/CountryGuessInput.svelte
<script lang="ts">
  import Button from '../button/Button.svelte';
  import {type GuessedCountries} from './CountryGuesser.svelte';
  import {type Countries} from './country';

  export let countries: Countries;
  export let guessedCountries: GuessedCountries;
  export let evaluateGuessAndUpdateState: (guessedCountry: string) => void;

  const countryHintsCount = 8;
  const countriesWithoutAlreadyGuessed: Countries = countries.filter(
    country => !guessedCountries.includes(country.name.common)
  );

  let filteredCountries: Countries = countriesWithoutAlreadyGuessed.slice(0, countryHintsCount);
  let currentGuess = '';
  let isOpen = false;
  let isValidGuess = false;
  let selectedGuessIndex = 0;

  const handleGuessButtonClick = () => {
    evaluateGuessAndUpdateState(currentGuess);
    handleChangeSelectedGuess('');
  };

  const handleChangeSelectedGuess = (guessedCountry: string) => {
    updateGuessAndFilteredCountries(guessedCountry);
    isOpen = false;
  };

  const handleInputChange = (event: Event) => {
    if (event.target instanceof HTMLInputElement) {
      const formattedGuess = convertToFormattedGuess(event.target.value);
      updateGuessAndFilteredCountries(formattedGuess);
    }
  };

  const handleKeyDown = (event: KeyboardEvent) => {
    if (!isOpen) return;

    if (event.key === 'ArrowUp') {
      changeSelectedGuessIndex(-1);
      event.preventDefault();
    } else if (event.key === 'ArrowDown') {
      changeSelectedGuessIndex(1);
      event.preventDefault();
    } else if (event.key === 'Enter' && filteredCountries.length > 0) {
      handleChangeSelectedGuess(filteredCountries[selectedGuessIndex].name.common);
    } else if (event.key === 'Escape') {
      isOpen = false;
    }
  };

  const updateGuessAndFilteredCountries = (guessedCountry: string) => {
    const _filteredCountries = getFilteredCountries(guessedCountry);

    currentGuess = guessedCountry;
    isValidGuess = !!filteredCountries.find(({name}) => name.common === guessedCountry);
    filteredCountries = _filteredCountries;
    clampSelectedGuessIndex(filteredCountries);
  };

  const getFilteredCountries = (guessedCountry: string) => {
    const filteredCountries = countriesWithoutAlreadyGuessed.filter(country =>
      country.name.common.toLowerCase().includes(guessedCountry.toLowerCase())
    );
    return filteredCountries.splice(0, countryHintsCount);
  };

  const clampSelectedGuessIndex = (filteredCountries: Countries) => {
    if (filteredCountries.length > 0 && selectedGuessIndex >= filteredCountries.length) {
      selectedGuessIndex = filteredCountries.length - 1;
    }
  };

  const changeSelectedGuessIndex = (value: number) => {
    if (selectedGuessIndex + value < 0) return;
    if (selectedGuessIndex + value >= filteredCountries.length) return;

    selectedGuessIndex += value;
  };

  const convertToFormattedGuess = (guess: string) => {
    const [firstLetter, ...rest] = guess;
    return firstLetter ? `${firstLetter.toUpperCase()}${rest.join('').toLowerCase()}` : '';
  };
</script>

<div class="relative group">
  <div class="flex">
    <input
      type="text"
      value={currentGuess}
      on:change={handleInputChange}
      on:click={() => {
        updateGuessAndFilteredCountries(currentGuess);
        isOpen = true;
      }}
      on:keydown={handleKeyDown}
      class="block rounded-md w-full p-2 shadow-sm bg-gray-100 border border-gray-400 lg:w-[20rem] xl:w-[24rem]"
    />

    <Button
      className="rounded-lg w-40 !p-2 grid place-content-center border border-gray-400 bg-green-800 text-white animate-pulse 
            lg:w-28 xl:w-32 hover:animate-none hover:bg-green-900 disabled:animate-none disabled:bg-red-800"
      onClick={handleGuessButtonClick}
      disabled={!isValidGuess}
    >
      Take a guess
    </Button>
  </div>

  <div
    class={`flex flex-col absolute top-18 w-full duration-150 opacity-0 pointer-events-none bg-gray-200 rounded-lg border border-gray-300 
          ${isOpen ? 'group-focus-within:opacity-100 group-focus-within:pointer-events-auto' : ''}`}
  >
    {#if filteredCountries.length > 0}
      {#each filteredCountries as filteredCountry, index}
        <Button
          key={index}
          onClick={() => handleChangeSelectedGuess(filteredCountry.name.common)}
          className={`rounded-lg p-2 ${selectedGuessIndex === index ? 'bg-gray-300' : ''}`}
        >
          {filteredCountry.flag}
          {filteredCountry.name.common}
        </Button>
      {/each}

      {#if filteredCountries.length === 1}
        <span class="rounded-lg p-2 text-center">
          Hit enter to select <b>{filteredCountries[0].name.common}</b>
        </span>
      {/if}
    {:else}
      <div class="rounded-lg p-2">No country found. Please, try to change your input.</div>
    {/if}
  </div>

  {#if !filteredCountries.length}
    <div class="rounded-lg mt-2">No country found. Please, try to change your input.</div>
  {/if}

  {#if currentGuess.length && filteredCountries.length && !isValidGuess}
    <div class="rounded-lg mt-2">Please enter/select a valid full country name.</div>
  {/if}

  {#if !currentGuess.length}
    <div class="rounded-lg mt-2">Enter a country you want to guess.</div>
  {/if}
</div>
