// apps/angular/src/app/components/country-guesser/country-guesser.component.ts
import {Component, Input} from '@angular/core';
import {Country} from './country';
import {HintBoxesComponent} from './hint-boxes/hint-boxes.component';

@Component({
  selector: 'country-guesser',
  standalone: true,
  templateUrl: './country-guesser.component.html',
  imports: [HintBoxesComponent],
})
export class CountryGuesserComponent {
  @Input() countries: ReadonlyArray<Country> = [];
}

<div class="container mx-auto space-y-6 sm:space-y-8">
  <hint-boxes
    [randomCountry]="countries[0]"
    [hintsEnabledCount]="8"
    class="grid grid-cols-3 md:grid-cols-4 lg:grid-cols-8 gap-2 sm:gap-4"
  />

  <div class="space-y-6 lg:flex lg:justify-center lg:gap-12 lg:space-y-0">
    <span>input</span>
    <span>list</span>
    <!-- <CountryGuessInput
            countries={countries}
            currentGuess={currentGuess}
            setCurrentGuess={setCurrentGuess}
            evaluateGuessAndUpdateState={evaluateGuessAndUpdateState}
            guessedCountries={guessedCountries}
          /> -->
    <!-- <GuessedCountriesList
            countries={countries}
            guessedCountries={guessedCountries}
            randomCountry={randomCountry}
          /> -->
  </div>
</div>

<!-- <WinModal
isOpen={isWinModalOpen}
handleClose={() => {
handleSetInitialState();
setIsWinModalOpen(false);
}}
randomCountry={randomCountry}
totalGuessesNeeded={totalGuessesNeeded}
/>
<LoseModal
isOpen={isLoseModalOpen}
handleClose={() => {
handleSetInitialState();
setIsLoseModalOpen(false);
}}
randomCountry={randomCountry}
/> -->

// apps/svelte/src/lib/components/country-guesser/CountryGuesser.svelte
<script lang="ts">
  import type {Countries} from './country';
  import HintBoxes from './hint-boxes/HintBoxes.svelte';

  export let countries: Countries;
</script>

<div class="container mx-auto space-y-6 sm:space-y-8">
  <div class="grid grid-cols-3 md:grid-cols-4 lg:grid-cols-8 gap-2 sm:gap-4">
    <HintBoxes randomCountry={countries[0]} hintsEnabledCount={8} />
  </div>

  <div class="space-y-6 lg:flex lg:justify-center lg:gap-12 lg:space-y-0">
    <span>CountryGuessInput</span>
    <!-- <CountryGuessInput
      {countries}
      {currentGuess}
      {guessedCountries}
      {setCurrentGuess}
      {evaluateGuessAndUpdateState}
    /> -->

    <span>GuessedCountriesList</span>
    <!-- <GuessedCountriesList {countries} {guessedCountries} {randomCountry} /> -->
  </div>
</div>

<!-- {isWinModalOpen ? (
<WinModal
randomCountry={randomCountry}
totalGuessesNeeded={totalGuessesNeeded}
handleClose={() => {
handleSetInitialState();
setIsWinModalOpen(false);
}}
/>
) : null}

{isLoseModalOpen ? (
<LoseModal
randomCountry={randomCountry}
handleClose={() => {
handleSetInitialState();
setIsLoseModalOpen(false);
}}
/>
) : null} -->
