// apps/react/src/components/CountryGuesser/CountryGuesser.tsx
import {useState} from 'react';
import {Country} from './useCountries';
import HintBoxes from './HintBoxes/HintBoxes';
import CountryGuessInput from './CountryGuessInput';
import WinModal from './Modals/WinModal';
import LoseModal from './Modals/LoseModal';
import {getRandomCountry} from './helpers';
import GuessedCountriesList from './GuessedCountriesList';

interface CountryGuesserProps {
  countries: ReadonlyArray<Country>;
}

const defaultHintsEnabledCount = 1;
const maximumCountryGuesses = 8;

function CountryGuesser({countries}: CountryGuesserProps) {
  const [randomCountry, setRandomCountry] = useState<Country>(() => getRandomCountry(countries));
  const [guessedCountries, setGuessedCountries] = useState<ReadonlyArray<string>>([]);
  const [currentGuess, setCurrentGuess] = useState('');
  const [hintsEnabledCount, setHintsEnabledCount] = useState(defaultHintsEnabledCount);
  const [totalGuessesNeeded, setTotalGuessesNeeded] = useState(1);
  const [isWinModalOpen, setIsWinModalOpen] = useState(false);
  const [isLoseModalOpen, setIsLoseModalOpen] = useState(false);
  console.log(`🚀 ~ CountryGuesser ~ randomCountry:`, randomCountry.name.common);

  const hasGuessedCountry = () => currentGuess === randomCountry.name.common;
  const hasReachedMaximumGuesses = () => guessedCountries.length + 1 === maximumCountryGuesses;

  const evaluateGuessAndUpdateState = () => {
    if (hasGuessedCountry()) {
      setHintsEnabledCount(maximumCountryGuesses);
      setTotalGuessesNeeded(guessedCountries.length + 1);
      setIsWinModalOpen(true);
      return;
    }

    if (hasReachedMaximumGuesses() && !hasGuessedCountry()) {
      setIsLoseModalOpen(true);
      return;
    }

    setCurrentGuess('');
    setGuessedCountries([...guessedCountries, currentGuess]);
    setHintsEnabledCount(hintsEnabledCount + 1);
  };

  const handleSetInitialState = () => {
    setRandomCountry(getRandomCountry(countries));
    setCurrentGuess('');
    setGuessedCountries([]);
    setHintsEnabledCount(defaultHintsEnabledCount);
  };

  return (
    <>
      <div className="container mx-auto space-y-6 sm:space-y-8">
        <div className="grid grid-cols-3 md:grid-cols-4 lg:grid-cols-8 gap-2 sm:gap-4">
          <HintBoxes randomCountry={randomCountry} hintsEnabledCount={hintsEnabledCount} />
        </div>

        <div className="space-y-6 lg:flex lg:justify-center lg:gap-12 lg:space-y-0">
          <CountryGuessInput
            countries={countries}
            currentGuess={currentGuess}
            setCurrentGuess={setCurrentGuess}
            evaluateGuessAndUpdateState={evaluateGuessAndUpdateState}
            guessedCountries={guessedCountries}
          />
          <GuessedCountriesList
            countries={countries}
            guessedCountries={guessedCountries}
            randomCountry={randomCountry}
          />
        </div>
      </div>

      <WinModal
        isOpen={isWinModalOpen}
        handleClose={() => {
          handleSetInitialState();
          setIsWinModalOpen(false);
        }}
        randomCountry={randomCountry}
        totalGuessesNeeded={totalGuessesNeeded}
      />
      <LoseModal
        isOpen={isLoseModalOpen}
        handleClose={() => {
          handleSetInitialState();
          setIsLoseModalOpen(false);
        }}
        randomCountry={randomCountry}
      />
    </>
  );
}

export default CountryGuesser;

// apps/svelte/src/lib/components/country-guesser/CountryGuesser.svelte
<script lang="ts" context="module">
  export type GuessedCountries = ReadonlyArray<string>;
</script>

<script lang="ts">
  import CountryGuessInput from './CountryGuessInput.svelte';
  import GuessedCountriesList from './GuessedCountriesList.svelte';
  import type {Countries, Country} from './country';
  import {getRandomCountry} from './helpers';
  import HintBoxes from './hint-boxes/HintBoxes.svelte';

  const defaultHintsEnabledCount = 1;
  const maximumCountryGuesses = 8;

  export let countries: Countries;

  let randomCountry: Country = getRandomCountry(countries);
  let guessedCountries: Array<string> = [];
  let hintsEnabledCount = defaultHintsEnabledCount;
  let totalGuessesNeeded = 1;
  let isWinModalOpen = false;
  let isLoseModalOpen = false;

  const handleEvaluateGuessAndUpdateState = (guessedCountry: string) => {
    console.log(`🚀 ~ handleEvaluateGuessAndUpdateState ~ guessedCountry:`, guessedCountry);

    if (hasGuessedCountry(guessedCountry)) {
      hintsEnabledCount = maximumCountryGuesses;
      totalGuessesNeeded = guessedCountries.length + 1;
      isWinModalOpen = true;
      return;
    }

    if (hasReachedMaximumGuesses() && !hasGuessedCountry(guessedCountry)) {
      isLoseModalOpen = true;
      return;
    }

    guessedCountries.push(guessedCountry);
    hintsEnabledCount++;
  };

  const handleSetInitialState = () => {
    randomCountry = getRandomCountry(countries);
    guessedCountries = [];
    hintsEnabledCount = defaultHintsEnabledCount;
  };

  const hasGuessedCountry = (guessedCountry: string) => {
    return randomCountry.name.common === guessedCountry;
  };

  const hasReachedMaximumGuesses = () => guessedCountries.length + 1 === maximumCountryGuesses;
</script>

<div class="container mx-auto space-y-6 sm:space-y-8">
  <div class="grid grid-cols-3 md:grid-cols-4 lg:grid-cols-8 gap-2 sm:gap-4">
    <HintBoxes {randomCountry} {hintsEnabledCount} />
  </div>

  <div class="space-y-6 lg:flex lg:justify-center lg:gap-12 lg:space-y-0">
    <CountryGuessInput
      {countries}
      {guessedCountries}
      evaluateGuessAndUpdateState={handleEvaluateGuessAndUpdateState}
    />

    <GuessedCountriesList {countries} {guessedCountries} {randomCountry} />
  </div>
</div>

<!-- {isWinModalOpen ? (
<WinModal
randomCountry={randomCountry}
totalGuessesNeeded={totalGuessesNeeded}
handleClose={() => {
handleSetInitialState();
setIsWinModalOpen(false);
}}
/>
) : null}

{isLoseModalOpen ? (
<LoseModal
randomCountry={randomCountry}
handleClose={() => {
handleSetInitialState();
setIsLoseModalOpen(false);
}}
/>
) : null} -->
