// apps/react/src/components/CountryGuesser/ErrorAlert.tsx
import {errorIcon} from '../icons/errorIcon';

interface ErrorAlertProps {
  message: string;
}

function ErrorAlert({message}: ErrorAlertProps) {
  return (
    <div
      className="flex items-center p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-200"
      role="alert"
    >
      {errorIcon}
      <span className="sr-only">Error</span>
      <p className="font-medium pl-2">{message}</p>
    </div>
  );
}

export default ErrorAlert;

// Inspiration:
// https://flowbite.com/docs/components/alerts/

// apps/svelte/src/lib/components/country-guesser/ErrorAlert.svelte
<script lang="ts">
  import ErrorIcon from '../icons/ErrorIcon.svelte';

  export let message: string;
</script>

<div class="flex items-center p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-200" role="alert">
  <ErrorIcon />
  <span class="sr-only">Error</span>
  <p class="font-medium pl-2">{message}</p>
</div>

<!-- Inspiration: -->
<!-- https://flowbite.com/docs/components/alerts/ -->
