// apps/angular/src/app/components/country-guesser/error-alert/error-alert.component.ts
import {Component, Input} from '@angular/core';
import {ErrorIconComponent} from '../../icons/error-icon/error-icon.component';

@Component({
  selector: 'error-alert',
  standalone: true,
  templateUrl: './error-alert.component.html',
  imports: [ErrorIconComponent],
})
export class ErrorAlertComponent {
  @Input() message = '';
}

<div class="flex items-center p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-200" role="alert">
  <error-icon />
  <span class="sr-only">Error</span>
  <p class="font-medium pl-2">{{ message }}</p>
</div>

<!-- Inspiration: -->
<!-- https://flowbite.com/docs/components/alerts/ -->

// apps/svelte/src/lib/components/country-guesser/ErrorAlert.svelte
<script lang="ts">
  import ErrorIcon from '../icons/ErrorIcon.svelte';

  export let message: string;
</script>

<div class="flex items-center p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-200" role="alert">
  <ErrorIcon />
  <span class="sr-only">Error</span>
  <p class="font-medium pl-2">{message}</p>
</div>

<!-- Inspiration: -->
<!-- https://flowbite.com/docs/components/alerts/ -->
