// apps/angular/src/app/components/country-guesser/loading-skeleton/loading-skeleton.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'loading-skeleton',
  standalone: true,
  templateUrl: './loading-skeleton.component.html',
})
export class LoadingSkeletonComponent {
  protected items = Array.from({length: 6});
}

<div role="status" class="animate-pulse">
  @for (item of items; track item) {
    <!-- $index reprezentuje aktuální index ve for smyčce. -->
    <div
      class="{{
        $index === 0 ? '!h-6' : 'h-4'
      }} bg-gray-300 rounded-full dark:bg-gray-400 w-full mt-4"
    ></div>
  }
  <span class="sr-only">Loading...</span>
</div>

<!-- Převzato a upraveno podle: -->
<!-- https://flowbite.com/docs/components/skeleton/ -->

// apps/svelte/src/lib/components/country-guesser/LoadingSkeleton.svelte
<script lang="ts">
  const items = Array.from({length: 6});
</script>

<div role="status" class="animate-pulse">
  {#each items as item, index}
    <div
      class={`${index === 0 ? '!h-6' : 'h-4'} 
        bg-gray-300 rounded-full dark:bg-gray-400 w-full mt-4`}
    ></div>
  {/each}
  <span class="sr-only">Loading...</span>
</div>

<!-- Převzato a upraveno podle: -->
<!-- https://flowbite.com/docs/components/skeleton/ -->
