// apps/angular/src/app/components/invest-form/invest-form.component.ts
import {CommonModule} from '@angular/common';
import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';
import {FormBuilder, FormControl, FormGroup, ReactiveFormsModule, Validators} from '@angular/forms';
import {FormFieldValues} from './formValues';
import {InputLabelComponent} from './input-label/input-label.component';

type InvestForm = FormGroup<{
  oneOffInvestment: FormControl<number | null>;
  investmentLength: FormControl<number | null>;
  averageSavingsInterest: FormControl<number | null>;
  averageSP500Interest: FormControl<number | null>;
}>;

@Component({
  selector: 'invest-form',
  standalone: true,
  templateUrl: './invest-form.component.html',
  imports: [CommonModule, ReactiveFormsModule, InputLabelComponent],
})
export class InvestFormComponent implements OnInit {
  // This is a workaround for disabling typescript problem e.g. with the initialization of investForm
  // that can be used instead of using ! in the investForm property declaration.
  // "compilerOptions": {
  //   ...
  //   "strictPropertyInitialization": false
  // },
  protected investForm!: InvestForm;

  @Input() defaultValues: FormFieldValues = {
    oneOffInvestment: 500,
    investmentLength: 10,
    averageSavingsInterest: 5,
    averageSP500Interest: 10,
  };

  @Output() formChanged = new EventEmitter<FormFieldValues>();

  constructor(private readonly fb: FormBuilder) {}

  public ngOnInit(): void {
    this.investForm = this.initializeInvestForm();
  }

  protected onSubmit(): void {
    this.formChanged.emit(this.investForm.value as FormFieldValues);
  }

  protected get oneOffInvestmentControl() {
    return this.investForm.controls.oneOffInvestment;
  }

  protected get investmentLengthControl() {
    return this.investForm.controls.investmentLength;
  }

  protected get averageSavingsInterestControl() {
    return this.investForm.controls.averageSavingsInterest;
  }

  protected get averageSP500InterestControl() {
    return this.investForm.controls.averageSP500Interest;
  }

  private initializeInvestForm() {
    return this.fb.group({
      oneOffInvestment: [
        this.defaultValues.oneOffInvestment,
        [Validators.required, Validators.min(20), Validators.max(99_999_999)],
      ],
      investmentLength: [
        this.defaultValues.investmentLength,
        [Validators.required, Validators.min(3), Validators.max(60)],
      ],
      averageSavingsInterest: [
        this.defaultValues.averageSavingsInterest,
        [Validators.required, Validators.min(0), Validators.max(10)],
      ],
      averageSP500Interest: [
        {value: this.defaultValues.averageSP500Interest, disabled: false},
        [Validators.required],
      ],
    });
  }
}

<form [formGroup]="investForm" (ngSubmit)="onSubmit()">
  <div class="md:flex md:gap-4">
    <div class="mb-4 md:w-1/2">
      <input-label id="oneOffInvestment">One-off investment (20-99.999.999€)</input-label>

      <input
        id="oneOffInvestment"
        type="number"
        formControlName="oneOffInvestment"
        class="mt-1 block w-full rounded-md p-2 shadow-sm bg-slate-100 border border-gray-300"
      />

      @if (oneOffInvestmentControl.errors?.['required']) {
        <p class="text-red-500 text-xs italic mt-1">
          Please enter a valid amount of one-off investment (positive number).
        </p>
      }
      @if (oneOffInvestmentControl.errors?.['min']) {
        <p class="text-red-500 text-xs italic mt-1">
          Please enter a valid amount of one-off investment (minimum 20 €).
        </p>
      }
      @if (oneOffInvestmentControl.errors?.['max']) {
        <p class="text-red-500 text-xs italic mt-1">
          Please enter a valid amount of one-off investment (maximum 99.999.999 €).
        </p>
      }
    </div>

    <div class="mb-4 md:w-1/2">
      <input-label id="investmentLength">Investment length (3-60 years)</input-label>

      <div class="flex">
        <input
          id="investmentLength"
          type="range"
          formControlName="investmentLength"
          min="3"
          max="60"
          class="mt-1 block w-full rounded-md p-2 shadow-sm bg-slate-100 border border-gray-300"
        />
        <div
          class="w-24 py-2 rounded-lg bg-slate-100 border border-gray-200 self-center text-center"
        >
          @if (investmentLengthControl.value) {
            {{ investmentLengthControl.value }} years
          }
        </div>
      </div>

      @if (investmentLengthControl.errors?.['required']) {
        <p class="text-red-500 text-xs italic mt-1">
          Please enter a valid length investment (positive number).
        </p>
      }
    </div>
  </div>

  <div class="md:flex md:gap-4">
    <div class="mb-4 md:w-1/2">
      <input-label id="averageSavingsInterest">
        Average interest on a savings account (0-10 %)
      </input-label>

      <input
        id="averageSavingsInterest"
        type="number"
        formControlName="averageSavingsInterest"
        step="0.1"
        class="mt-1 block w-full rounded-md p-2 shadow-sm bg-slate-100 border border-gray-300"
      />

      @if (averageSavingsInterestControl.errors?.['required']) {
        <p class="text-red-500 text-xs italic mt-1">
          Please enter a valid average amount of interest on savings account (non-negative number).
        </p>
      }
      @if (averageSavingsInterestControl.errors?.['min']) {
        <p class="text-red-500 text-xs italic mt-1">
          Please enter a valid average amount of interest on savings account (minimum 0 %).
        </p>
      }
      @if (averageSavingsInterestControl.errors?.['max']) {
        <p class="text-red-500 text-xs italic mt-1">
          Please enter a valid average amount of interest on savings account (maximum 10 %).
        </p>
      }
    </div>

    <div class="mb-4 md:w-1/2">
      <input-label id="averageSP500Interest">
        Average S&P 500 yield (approximate value in %)
      </input-label>

      <input
        id="averageSP500Interest"
        type="number"
        formControlName="averageSP500Interest"
        class="mt-1 block w-full rounded-md p-2 shadow-sm bg-slate-100 border border-gray-300 cursor-not-allowed opacity-70"
        readOnly
      />

      @if (averageSP500InterestControl.errors?.['required']) {
        <p class="text-red-500 text-xs italic mt-1">
          Please enter a valid average amount of S&P 500 yield (non-negative number).
        </p>
      }
    </div>
  </div>

  <button
    type="submit"
    [disabled]="investForm.invalid"
    class="w-full px-4 py-2 mr-2 bg-blue-500 text-white rounded-md shadow-sm hover:bg-blue-700 disabled:opacity-50"
  >
    Calculate
  </button>
</form>

// apps/svelte/src/lib/components/invest-form/InvestForm.svelte
<script lang="ts">
  import {createForm} from 'svelte-forms-lib';
  import {object, number} from 'yup';
  import {type InvestFormData} from './types';
  import InputLabel from './InputLabel.svelte';

  export let investFormData: InvestFormData | undefined;
  export let defaultValues: InvestFormData = {
    oneOffInvestment: 500,
    investmentLength: 10,
    averageSavingsInterest: 5,
    averageSP500Interest: 10,
  };

  const validationSchema = object().shape({
    oneOffInvestment: number().min(20).max(99_999_999).required(),
    investmentLength: number().min(3).max(60).required(),
    averageSavingsInterest: number().min(0).max(10).required(),
    averageSP500Interest: number().required(),
  });

  const {form, errors, isValid, handleChange, handleSubmit} = createForm({
    initialValues: defaultValues,
    validationSchema,
    onSubmit: values => {
      investFormData = validationSchema.cast(values);
    },
  });
</script>

<form on:submit={handleSubmit}>
  <div class="md:flex md:gap-4">
    <div class="mb-4 md:w-1/2">
      <InputLabel id="oneOffInvestment">One-off investment (20-99.999.999€)</InputLabel>

      <input
        id="oneOffInvestment"
        type="number"
        on:change={handleChange}
        bind:value={$form.oneOffInvestment}
        class="mt-1 block w-full rounded-md p-2 shadow-sm bg-slate-100 border border-gray-300"
      />

      {#if $errors.oneOffInvestment}
        <p class="text-red-500 text-xs italic mt-1">
          Please enter a valid amount of one-off investment (positive number).
        </p>
      {/if}
    </div>

    <div class="mb-4 md:w-1/2">
      <InputLabel id="investmentLength">Investment length (3-60 years)</InputLabel>

      <div class="flex">
        <input
          id="investmentLength"
          type="range"
          min="3"
          max="60"
          on:change={handleChange}
          bind:value={$form.investmentLength}
          class="mt-1 block w-full rounded-md p-2 shadow-sm bg-slate-100 border border-gray-300"
        />

        <div
          class="w-24 py-2 rounded-lg bg-slate-100 border border-gray-200 self-center text-center"
        >
          {$form.investmentLength} years
        </div>
      </div>

      {#if $errors.investmentLength}
        <p class="text-red-500 text-xs italic mt-1">
          Please enter a valid length investment (positive number).
        </p>
      {/if}
    </div>
  </div>

  <div class="md:flex md:gap-4">
    <div class="mb-4 md:w-1/2">
      <InputLabel id="averageSavingsInterest">
        Average interest on a savings account (0-10 %)
      </InputLabel>

      <input
        id="averageSavingsInterest"
        type="number"
        step={0.1}
        on:change={handleChange}
        bind:value={$form.averageSavingsInterest}
        class="mt-1 block w-full rounded-md p-2 shadow-sm bg-slate-100 border border-gray-300"
      />

      {#if $errors.averageSavingsInterest}
        <p class="text-red-500 text-xs italic mt-1">
          Please enter a valid average amount of interest on savings account (non-negative number).
        </p>
      {/if}
    </div>

    <div class="mb-4 md:w-1/2">
      <InputLabel id="averageSP500Interest">
        Average S&P 500 yield (approximate value in %)
      </InputLabel>

      <input
        id="averageSP500Interest"
        type="number"
        on:change={handleChange}
        bind:value={$form.averageSP500Interest}
        class="mt-1 block w-full rounded-md p-2 shadow-sm bg-slate-100 border border-gray-300 cursor-not-allowed opacity-70"
        disabled
        readOnly
      />

      {#if $errors.averageSP500Interest}
        <p class="text-red-500 text-xs italic mt-1">
          Please enter a valid average amount of S&P 500 yield (non-negative number).
        </p>
      {/if}
    </div>
  </div>

  <button
    type="submit"
    disabled={!$isValid}
    class="w-full px-4 py-2 mr-2 bg-blue-500 text-white rounded-md shadow-sm hover:bg-blue-700 disabled:opacity-50"
  >
    Calculate
  </button>
</form>
