// apps/react/src/components/InvestForm/FutureValueInfo.tsx
import {ReactNode} from 'react';

interface FutureValueInfoProps {
  futureValue: number;
  children: ReactNode;
}

const getLocalizedNumber = (value: number): string => `${value.toLocaleString('de-DE')}€`;

function FutureValueInfo({children, futureValue}: FutureValueInfoProps) {
  return (
    <div className="p-1 sm:w-1/2">
      <p className="text-xl font-semibold mb-2 text-gray-800">{children}</p>
      <p className="text-5xl font-bold">{getLocalizedNumber(futureValue)}</p>
    </div>
  );
}

export default FutureValueInfo;

// apps/angular/src/app/components/invest-form/future-value-info/future-value-info.component.ts
import {CommonModule} from '@angular/common';
import {Component, Input} from '@angular/core';

@Component({
  selector: 'future-value-info',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './future-value-info.component.html',
})
export class FutureValueInfoComponent {
  protected localizedFutureValue = 'No localized future value set!';

  @Input({required: true}) set futureValue(value: number) {
    this.localizedFutureValue = this.getLocalizedNumber(value);
  }

  private getLocalizedNumber(value: number): string {
    return `${value.toLocaleString('de-DE')}€`;
  }
}

<p class="text-xl font-semibold mb-2 text-gray-800">
  <ng-content />
</p>
<p class="text-5xl font-bold">{{ localizedFutureValue }}</p>
