// apps/react/src/components/CountryGuesser/GuessedCountriesList.tsx
import {getGuessedCountriesWithAdditionalProps} from './helpers';
import {Countries, Country} from './country';
import {GuessedCountries} from './CountryGuesser';

interface GuessedCountriesListProps {
  countries: Countries;
  guessedCountries: GuessedCountries;
  randomCountry: Country;
}

function GuessedCountriesList({
  countries,
  guessedCountries,
  randomCountry,
}: GuessedCountriesListProps) {
  const guessedCountriesWithAdditionalProps = getGuessedCountriesWithAdditionalProps(
    countries,
    guessedCountries,
    randomCountry,
  );

  return (
    <div className="border-t border-gray-300 pt-4 lg:border-t-0 lg:pt-0">
      <h2 className="text-xl font-bold mb-3">Guessed countries</h2>

      <div className="flex flex-col w-full lg:w-[27rem] xl:w-[32rem]">
        {guessedCountriesWithAdditionalProps.length > 0 ? (
          <ul className="space-y-2">
            {guessedCountriesWithAdditionalProps.map((country, index) => (
              <li key={index} className="flex justify-between rounded-md bg-gray-100 p-1.5">
                <span>
                  {index + 1}. {country.name} {country.flag}
                </span>
                <span>{country.distanceAway} km away</span>
              </li>
            ))}
          </ul>
        ) : (
          <p>No country guessed yet. Please, take a guess!</p>
        )}
      </div>

      {guessedCountriesWithAdditionalProps.length > 0 ? (
        <p className="mt-4">Away distance is calculated from the center of each country.</p>
      ) : null}
    </div>
  );
}

export default GuessedCountriesList;

// apps/angular/src/app/components/country-guesser/guessed-countries-list/guessed-countries-list.component.ts
import {Component, Input, OnChanges} from '@angular/core';
import {Country} from '../country';
import {
  GuessedCountriesWithAdditionalProps,
  getGuessedCountriesWithAdditionalProps,
} from '../helpers';

@Component({
  selector: 'guessed-countries-list',
  standalone: true,
  templateUrl: './guessed-countries-list.component.html',
})
export class GuessedCountriesListComponent implements OnChanges {
  protected guessedCountriesWithAdditionalProps: GuessedCountriesWithAdditionalProps = [];

  @Input({required: true}) countries: ReadonlyArray<Country> = [];
  @Input({required: true}) guessedCountries: ReadonlyArray<string> = [];
  @Input({required: true}) randomCountry!: Country;

  public ngOnChanges(): void {
    this.guessedCountriesWithAdditionalProps = getGuessedCountriesWithAdditionalProps(
      this.countries,
      this.guessedCountries,
      this.randomCountry,
    );
  }
}

<div class="border-t border-gray-300 pt-4 lg:border-t-0 lg:pt-0">
  <h2 class="text-xl font-bold mb-3">Guessed countries</h2>

  <div class="flex flex-col w-full lg:w-[27rem] xl:w-[32rem]">
    @if (guessedCountriesWithAdditionalProps.length > 0) {
      <ul class="space-y-2">
        @for (country of guessedCountriesWithAdditionalProps; track country) {
          <li key="{index}" class="flex justify-between rounded-md bg-gray-100 p-1.5">
            <span> {{ $index + 1 }}. {{ country.name }} {{ country.flag }} </span>
            <span>{{ country.distanceAway }} km away</span>
          </li>
        }
      </ul>
    } @else {
      <p>No country guessed yet. Please, take a guess!</p>
    }
  </div>

  @if (guessedCountriesWithAdditionalProps.length > 0) {
    <p class="mt-4">Away distance is calculated from the center of each country.</p>
  }
</div>
