// apps/react/src/components/Translator/TranslationInput.tsx
import {ChangeEvent, useRef} from 'react';
import {closeIcon} from '../../assets/svg/close';
import useAutosizeTextArea from './useAutoresizeTextarea';

interface TranslationInputProps {
  inputText: string;
  setInputText: (inputText: string) => void;
}

function TranslationInput({inputText, setInputText}: TranslationInputProps) {
  const textAreaRef = useRef<HTMLTextAreaElement>(null);

  const maximumCharactersCount = 800;

  useAutosizeTextArea(textAreaRef.current, inputText);

  const handleInputChange = ({target}: ChangeEvent<HTMLTextAreaElement>) => {
    if (target.value.length <= maximumCharactersCount) {
      setInputText(target.value);
    }
  };

  return (
    <div className='relative w-1/2'>
      <div className='border h-full'>
        <textarea
          ref={textAreaRef}
          className='block w-full min-h-0 p-3 pr-12 pb-8 resize-none !outline-none'
          placeholder='Type to translate ...'
          value={inputText}
          onChange={handleInputChange}
        />
      </div>

      {inputText.length ? (
        <button
          className='absolute top-2 right-2 text-gray-500 text-sm p-1.5 hover:bg-gray-100'
          onClick={() => setInputText('')}
        >
          {closeIcon}
        </button>
      ) : null}

      <span className='absolute bottom-2 right-2 text-gray-500 text-sm'>
        {inputText.length} / {maximumCharactersCount} characters
      </span>
    </div>
  );
}

export default TranslationInput;

// apps/angular/src/app/components/translator/translation-input/translation-input.component.ts
import {CommonModule} from '@angular/common';
import {Component, ElementRef, EventEmitter, Input, Output, ViewChild} from '@angular/core';
import {CloseIconComponent} from './close-icon/close-icon.component';

@Component({
  selector: 'translation-input',
  standalone: true,
  templateUrl: './translation-input.component.html',
  imports: [CommonModule, CloseIconComponent],
})
export class TranslationInputComponent {
  protected maximumCharactersCount = 800;

  @Input() public inputText = '';

  @Output() public setInputText = new EventEmitter<string>();

  @ViewChild('textAreaRef') textAreaRef!: ElementRef;

  protected handleInputChange(event: Event): void {
    const target = event.target as HTMLTextAreaElement;

    if (target.value.length <= this.maximumCharactersCount) {
      this.setInputText.emit(target.value);
    }
  }
}

<div class="border h-full">
  <div class="block w-full"></div>
  <textarea
    #textAreaRef
    class="block w-full min-h-0 p-3 pr-12 pb-8 resize-none !outline-none"
    placeholder="Type to translate ..."
    [value]="inputText"
    (input)="handleInputChange($event)"
  >
  </textarea>
</div>

<button
  *ngIf="inputText.length"
  class="absolute top-2 right-2 text-gray-500 text-sm p-1.5 hover:bg-gray-100"
  (click)="setInputText.emit('')"
>
  <close-icon />
</button>

<span class="absolute bottom-2 right-2 text-gray-500 text-sm">
  {{ inputText.length }} / {{ maximumCharactersCount }} characters
</span>
