// apps/angular/src/app/app.component.ts
import {CommonModule} from '@angular/common';
import {Component} from '@angular/core';
import {RouterOutlet} from '@angular/router';
import {CounterComponent} from "./components/counter/counter.component";
import {DropdownComponent, Option} from './components/dropdown/dropdown.component';
import {DropdownVariant} from './components/dropdown/dropdownVariants';
import {DropdownSize} from './components/dropdown/dropdownSize';

@Component({
    selector: 'app-root',
    standalone: true,
    templateUrl: './app.component.html',
    imports: [CommonModule, RouterOutlet, CounterComponent, DropdownComponent]
})
export class AppComponent {
  protected dropdownVariants: ReadonlyArray<DropdownVariant> = [
    'primary',
    'secondary',
    'neutral',
    'light',
    'dark',
    'info',
    'success',
    'warning',
    'error',
  ];
  protected colors: ReadonlyArray<Option> = [
    {label: 'Alice Blue', value: '#F0F8FF'},
    {label: 'Antique White', value: '#FAEBD7'},
    {label: 'Aqua', value: '#00FFFF'},
    {label: 'Aquamarine', value: '#7FFFD4'},
    {label: 'Azure', value: '#F0FFFF'},
    {label: 'Beige', value: '#F5F5DC'},
  ];
  protected sizes: ReadonlyArray<DropdownSize> = ['sm', 'md', 'lg'];

  protected selectedColor: Option | null = null;

  protected onDropdownChange(selectedColor: Option): void {
    this.selectedColor = selectedColor;
  }
}

<main class="main">
  <h1>Angular Landing Page</h1>
  
  <counter />

  <div *ngFor="let size of sizes" class="flex gap-2 justify-center items-center h-20">
    <dropdown
      *ngFor="let variant of dropdownVariants"
      [options]="colors"
      [defaultValue]="selectedColor"
      placeholder="Select a color"
      (onChange)="onDropdownChange($event)"
      [variant]="variant"
      [size]="size"
    />
  </div>
</main>

<router-outlet></router-outlet>

// apps/svelte/src/App.svelte
<script lang="ts">
  import Counter from './lib/components/Counter.svelte';
  import Dropdown, {type Option} from './lib/components/dropdown/Dropdown.svelte';
  import type {DropdownSize} from './lib/components/dropdown/dropdownSize';
  import {type DropdownVariant} from './lib/components/dropdown/dropdownVariants';

  const dropdownVariants: ReadonlyArray<DropdownVariant> = [
    'primary',
    'secondary',
    'neutral',
    'light',
    'dark',
    'info',
    'success',
    'warning',
    'error',
  ];

  const colors = [
    {label: 'Alice Blue', value: '#F0F8FF'},
    {label: 'Antique White', value: '#FAEBD7'},
    {label: 'Aqua', value: '#00FFFF'},
    {label: 'Aquamarine', value: '#7FFFD4'},
    {label: 'Azure', value: '#F0FFFF'},
    {label: 'Beige', value: '#F5F5DC'},
  ];

  const sizes: ReadonlyArray<DropdownSize> = ['sm', 'md', 'lg'];

  let selectedColor: Option | null = null;
</script>

<main>
  <h1>Svelte Landing Page</h1>

  <Counter />

  {#each sizes as size}
    <div class="flex gap-2 justify-center items-center h-20">
      {#each dropdownVariants as variant}
        <Dropdown
          options={colors}
          defaultValue={selectedColor}
          placeholder="Select a color"
          onChange={option => (selectedColor = option)}
          {size}
          {variant}
        />
      {/each}
    </div>
  {/each}
</main>
